- name: DNAC Compliance Demo
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault.yml
  vars:
    dnac_host: none
    dnac_username: "{{username}}"
    dnac_password: "{{password}}"
    dnac_verify: False
    dnac_version: 2.2.2.3
    dnac_debug: False
    dnac_port: 443
    device_name: none
    cli_template: ""

  tasks:
  - name: Get timestamp from the system
    shell: "date +%Y-%m-%dT%H-%M-%S"
    register: tstamp
    delegate_to: localhost

  - name: Get Compliance configuration template projects
    cisco.dnac.configuration_template_project_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      name: Compliance
    register: compliance_projects

  - name: Print compliance project id
    ansible.builtin.debug:
      msg: "Compliance Project ID is: {{compliance_projects.dnac_response[0].id}}"

  - name: "Create compliance-{{device_name}}-{{ tstamp.stdout }} template"
    cisco.dnac.configuration_template_create:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      name: "compliance-{{device_name}}-{{ tstamp.stdout }}"
      tags: []
      author: Ansible
      deviceTypes:
        - productFamily: Routers
        - productFamily: Switches and Hubs
      softwareType: IOS-XE
      softwareVariant: XE
      templateContent: "{{cli_template}}"
      rollbackTemplateContent:
      rollbackTemplateParams: []
      projectId: "{{compliance_projects.dnac_response[0].id}}"
      language: JINJA
    register: create_configuration_template_response

  # - name: Print task information
  #   ansible.builtin.debug:
  #     msg: "{{create_configuration_template_response}}"

  - name: Sleep for 30 seconds and continue with play
    wait_for:
      timeout: 30
    delegate_to: localhost

  - name: Get task information
    cisco.dnac.task_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      taskId: "{{create_configuration_template_response.dnac_response.response.taskId}}"
    register: task_info

  - name: Print template ID
    ansible.builtin.debug:
      msg: "Template ID is {{task_info.dnac_response.response.data}}"

  - name: "Commit template compliance-{{device_name}}-{{ tstamp.stdout }} id"
    cisco.dnac.configuration_template_version_create:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      comments: "First commit"
      templateId: "{{task_info.dnac_response.response.data}}"

  - name: Sleep for 10 seconds and continue with play
    wait_for:
      timeout: 10
    delegate_to: localhost

  - name: "Deploy configuration to device {{ device_name }}"
    cisco.dnac.configuration_template_deploy_v2:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      forcePushTemplate: true
      isComposite: false
      templateId: "{{task_info.dnac_response.response.data}}"
      targetInfo:
        - id: "{{device_name}}"
          type: "MANAGED_DEVICE_HOSTNAME"
    register: template_deployment_task

  - name: Sleep for 30 seconds and continue with play
    wait_for:
      timeout: 30
    delegate_to: localhost

  - name: Get template deployment task information
    cisco.dnac.task_info:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      taskId: "{{template_deployment_task.dnac_response.response.taskId}}"
    register: task_info

  - name: Print task information id
    ansible.builtin.debug:
      msg: "Deployment progress is {{task_info.dnac_response.response.progress}}"

